# Generated by Django 5.1.2 on 2025-05-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_formation_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicPath',
        ),
    ]
