# Generated by Django 5.1.2 on 2025-05-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_delete_academicpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='ressources_pedagogiques',
            field=models.TextField(blank=True),
        ),
    ]
